version: "3.9"

services:
  mysql-db:
    # Build local para garantir que o school.sql é incluído
    build: ../mysql-db 
    image: inf24dw1g10/mysql-db:m3
    container_name: mysql-db
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - schoolnet

  api-horarios:
    build: ../parte-3-m3 # Caminho para a pasta da API Loopback
    image: inf24dw1g10/api-horarios:m3
    container_name: api-horarios
    depends_on:
      - mysql-db
    environment:
      DB_HOST: mysql-db
      DB_USER: root
      DB_PASSWORD: Igor1234!
      DB_NAME: school
    ports:
      - "8080:3000"
    networks:
      - schoolnet

  react-admin:
    build: ../admin
    image: inf24dw1g10/react-admin:m3
    container_name: react-admin
    ports:
      - "3001:80"
    networks:
      - schoolnet

volumes:
  mysql_data:

networks:
  schoolnet: